package handler

// Poems data - compiled into binary for maximum speed
var products = []Product{
	{1, "Morning Coffee", "MORN-001", 0.15, "Daily Life", "The steam rises like morning mist over a quiet lake"},
	{2, "City Rain", "RAIN-002", 12.50, "Urban", "Concrete absorbs the sky's tears, becoming something new"},
	{3, "Old Books", "BOOK-003", 8.75, "Memory", "Pages whisper secrets that time has forgotten"},
	{4, "Empty Streets", "STRE-004", 0.05, "Solitude", "Lamplight creates shadows where footsteps used to be"},
	{5, "Garden Soil", "GARD-005", 3.25, "Nature", "Dark earth holds the promise of tomorrow's green"},
	{6, "Winter Wind", "WIND-006", 5.99, "Seasons", "Cold fingers trace patterns on frosted window glass"},
	{7, "Train Whistle", "TRAI-007", 0.08, "Journey", "Distance calls through steel and steam, carrying dreams away"},
	{8, "Kitchen Table", "KITC-008", 15.99, "Home", "Wood grain tells stories of meals and conversations"},
	{9, "Streetlight", "STRE-009", 2.50, "Night", "Electric stars guide the lost back to themselves"},
	{10, "River Stone", "RIVE-010", 8.99, "Water", "Smooth edges shaped by time's patient hands"},
	{11, "Library Silence", "LIBR-011", 12.99, "Quiet", "Words rest between covers, waiting to be awakened"},
	{12, "Bicycle Bell", "BICY-012", 0.12, "Movement", "Tiny chime announces freedom on two wheels"},
	{13, "Window Sill", "WIND-013", 18.50, "Threshold", "Boundary between inside dreams and outside world"},
	{14, "Coffee Shop", "COFF-014", 9.99, "Gathering", "Steam and conversation blend in warm air"},
	{15, "Park Bench", "PARK-015", 25.99, "Rest", "Wooden seat witnesses countless human stories"},
	{16, "Mailbox", "MAIL-016", 7.99, "Connection", "Metal mouth swallows words meant for distant hearts"},
	{17, "Fire Escape", "FIRE-017", 0.35, "Escape", "Iron ladder leads to sky and possibility"},
	{18, "Typewriter", "TYPE-018", 45.99, "Writing", "Metal keys strike paper with intention and purpose"},
	{19, "Street Vendor", "VEND-019", 12.99, "Commerce", "Small cart carries big dreams and daily bread"},
	{20, "Laundry Line", "LAUN-020", 4.99, "Domestic", "Clothes dance with wind, telling stories of wear"},
	{21, "Door Knob", "DOOR-021", 8.99, "Entry", "Brass circle opens worlds beyond the threshold"},
	{22, "Newspaper", "NEWS-022", 0.28, "Information", "Ink and paper capture moments before they fade"},
	{23, "Umbrella", "UMBR-023", 22.99, "Protection", "Fabric shield against the sky's unpredictable moods"},
	{24, "Tea Cup", "TEAC-024", 1.25, "Ritual", "Porcelain holds warmth and quiet contemplation"},
	{25, "Brick Wall", "BRIC-025", 0.75, "Foundation", "Red clay baked into permanence and strength"},
	{26, "Clock Tower", "CLOC-026", 1.99, "Time", "Stone face marks the passage of all things"},
	{27, "Garden Gate", "GATE-027", 0.06, "Transition", "Wooden barrier between wild and cultivated"},
	{28, "Street Sign", "SIGN-028", 19.99, "Direction", "Metal guide pointing toward unknown destinations"},
	{29, "Window Box", "WIND-029", 1.99, "Beauty", "Small garden reaching toward light and sky"},
	{30, "Bicycle Wheel", "WHEE-030", 2.99, "Motion", "Perfect circle spinning through space and time"},
	{31, "Ear Plugs", "EARP-031", 0.25, "Silence", "Soft barriers against the world's constant noise"},
	{32, "Screwdriver", "SCRE-032", 0.18, "Repair", "Metal tool mending what time has broken"},
	{33, "Tape Measure", "TAPE-033", 12.99, "Precision", "Flexible ruler defining the boundaries of space"},
	{34, "Wire Nuts", "WIRE-034", 0.15, "Connection", "Small caps joining separate paths into one"},
	{35, "Pipe Fitting", "PIPE-035", 4.25, "Flow", "Metal joint directing water's journey through walls"},
	{36, "Safety Glasses", "SAFE-036", 6.99, "Vision", "Clear lenses protecting sight from harm"},
	{37, "Wood Screws", "WOOD-037", 0.22, "Fastening", "Spiral threads holding pieces together"},
	{38, "Hammer", "HAMM-038", 15.99, "Force", "Weighted tool shaping the world through impact"},
	{39, "Electrical Outlet", "ELEC-039", 18.99, "Power", "Metal portal channeling invisible energy"},
	{40, "Pipe Wrench", "PIPE-040", 19.99, "Grip", "Jawed tool holding tight to what must be turned"},
	{41, "First Aid Kit", "FIRS-041", 24.99, "Healing", "Box of remedies for life's small wounds"},
	{42, "Eye Bolts", "EYEB-042", 1.25, "Anchor", "Metal loops securing things to solid ground"},
	{43, "Utility Knife", "UTIL-043", 8.99, "Cutting", "Sharp blade dividing what is from what will be"},
	{44, "Wire Nuts", "WIRE-044", 0.15, "Joining", "Small caps uniting separate strands into one"},
	{45, "Pipe Fitting", "PIPE-045", 5.99, "Direction", "Metal guide steering water's flow"},
	{46, "Reflective Tape", "REFL-046", 3.99, "Visibility", "Bright strips making the unseen seen"},
	{47, "Anchor Bolts", "ANCH-047", 0.45, "Foundation", "Metal roots holding structures to earth"},
	{48, "Chisel Set", "CHIS-048", 28.99, "Sculpting", "Sharp tools carving beauty from raw material"},
	{49, "Electrical Panel", "ELEC-049", 89.99, "Control", "Metal box containing the power of light"},
	{50, "Pipe Fitting", "PIPE-050", 7.99, "Conduit", "Metal passage allowing flow between spaces"},
}
